# Generated by Django 2.2.1 on 2019-05-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fibonaccimodel',
            name='Number',
        ),
        migrations.AddField(
            model_name='fibonaccimodel',
            name='number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='number'),
        ),
    ]
